### ISSUE TITLE
cgroupv2 option

### ISSUE THREAD

**Issue by cwjackso** [allfro/device-mapping-manager#3]
Great work on this plugin so far. I'm not a go developer and have little knowledge of cgroups however thought it would be useful to point out the work done by nvidia on this front

Here is the implementation they have for mounting hardware in [cgroupv1](https://github.com/NVIDIA/libnvidia-container/blob/465b98010f4235e751424e04577b0f27bd496c0d/src/nvcgo/internal/cgroup/v1.go) and[ cgroupv2](https://github.com/NVIDIA/libnvidia-container/blob/465b98010f4235e751424e04577b0f27bd496c0d/src/nvcgo/internal/cgroup/v2.go)

**Comment by allfro** [comment]
That's awesome. The cgroupv2 code is exactly what I was looking for. I'll try to integrate that soon.

**Comment by cwjackso** [comment]
Great - glad I could help!

**Comment by allfro** [comment]
Thanks for the pointers. The code has now been adjusted to work with cgroupv2. The deployment model has changed.
